#+TITLE: Emacs Init
#+OPTIONS: toc:2 num:nil ^:nil
#+STARTUP:  hideblocks

#+begin_quote
  Emacs outshines all other editing software in approximately the same
  way that the noonday sun does the stars. It is not just bigger and
  brighter; it simply makes everything else vanish.

  -- Neal Stephenson, "In the Beginning was the Command Line"
#+end_quote

* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END:
  - emacs24-starter-kit ::
    This file is an inspired by version of the emacs24-starter-kit.
    The latest version can be found at http://github.com/eschulte/emacs24-starter-kit/
    #+begin_src sh
      git clone https://github.com/eschulte/emacs24-starter-kit.git
    #+end_src
    
    If you want to keep your regular =~/.emacs.d= in place and just launch
    a single instance using the starter kit, try the following invocation:
    #+begin_src sh
      emacs -q -l ~/src/emacs24-starter-kit/init.el
    #+end_src

** Why modify the emacs24-starter-kit?
   The reasons are simple. I want a "me" centered emacs initialization
   rather then a starter-kit centered one. This means that I should be
   able to use it the way i feel works for me. Another reason is that
   introducing alot of new "features" which I haven't tested makes
   emacs work very far from factory settings without me knowing what
   is what or where it originated from.
** Structure
   :PROPERTIES:
   :CUSTOM_ID: structure
   :END:
   The =init.el= file is where everything begins. It is loaded
   automatically by Emacs on startup, its sole purpose is to load the
   elisp code embedded in this file.  This file then loads some core
   configurations and packages which should be generally useful, and
   goes on to load user-specific configuration files from the
   following locations mentioned in [[customization]] immediately below.

** Customization
   :PROPERTIES:
   :CUSTOM_ID: customization
   :tangle:   no
   :END:

   The defaults built into the emacs init are only the beginning of
   most users customization of Emacs to suite their needs.  This file
   provides a number of places for additional user and system
   specific customization.

   - User specific config :: Your personal configuration information can
	be stored in a user-specific-config file.  This is the file named
	after your user with the extensions =.el= or =.org= [2].  If
	you're unsure of your user name evaluate the following code block
	to find out.
     #+begin_src sh
       echo $USER
     #+end_src

	If your configuration starts to feel cramped in a single file
	(although with the nested headlines of an Org-mode file, that
	could take a while) and you want to stretch your config's legs,
	you can also create a directory named after your system user
	name.  If a such a directory exists, it will be added to the
	load-path, and any elisp or org-mode w/embedded elisp files in it
	will be loaded.

   - System specific config :: Finally, you may want to configure
	different settings for different machines.  The Emacs Init will
	look for a file named after the current hostname ending in =.el=
	or =.org= which will allow host-specific configuration. If
	you're unsure of your hostname the following can be executed to
	find out.
     #+begin_src sh
       hostname
     #+end_src

   - Installing more elisp libraries :: The easiest way to install new
        libraries is through the Emacs Lisp Package Archive (see
        [[#emacs-lisp-package-archive][EmacsLisp Package Archive]] below).  When a library is not
        available through ELPA you can grab it's source and place it
        directly in the =src= directory. Any packages found there will
        automatically be added to your load-path when Emacs starts
        up. I also install packages through el-get.

   - Misc :: Some additional miscellaneous configuration and getting
	     started suggestions
     - First see the [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Customization.html#Customization][Customization]] node in the Emacs manual. Available
       online or through the =info= command (run with =C-h i=).
     - read the following [[http://www.gnu.org/software/emacs/elisp/html_node/Key-Binding-Conventions.html][Key-Binding-Conventions]] before defining too
       many personal key bindings

** Emacs Lisp Package Archive
   :PROPERTIES:
   :CUSTOM_ID: emacs-lisp-package-archive
   :END:

   Libraries from [[http://tromey.com/elpa][ELPA]] are preferred when available since dependencies
   are handled automatically, and the burden to update them is removed
   from the user. ELPA is now an official part of Emacs so no special
   configuration is required to download and install packages.  Packages
   installed through ELPA will be stored in the =elpa/= sub-directory of
   this directory.

** El-get
   El-get is a package manager for using custome recipes for
   installing emacs packages. The source can be fetched [[https://github.com/dimitri/el-get][here]], by doing:
   #+begin_src sh
     git clone https://github.com/dimitri/el-get.git
   #+end_src
   This can be automated with a [[Lazy%20install][Lazy install]] or regular [[Install]].

* Implementation
  :PROPERTIES:
  :CUSTOM_ID: implementation
  :END:

  This section contains all code implemented in Emacs Init. It
  is probably safe to stop reading at this point unless you are
  interested in the actual code implemented in Emacs Init.

** emacs init basics
   - Load path etc.
     #+name: emacs-init-load-paths
     #+begin_src emacs-lisp
       (add-to-list 'load-path emacs-init-dir)
       (setq autoload-file (concat emacs-init-dir "loaddefs.el"))
       (setq package-user-dir (concat emacs-init-dir "elpa"))
       (setq custom-file (concat emacs-init-dir "custom.el"))
     #+end_src

   - Ubiquitous Packages which should be loaded on startup rather than
     autoloaded on demand since they are likely to be used in every
     session.
     #+name: emacs-init-load-on-startup
     #+begin_src emacs-lisp tangle: yes
       (require 'saveplace)
       (require 'ffap)
       (require 'uniquify)
       (require 'ansi-color)
       (require 'recentf)
     #+end_src

   - ELPA archive repositories. 
     #+begin_src emacs-lisp
       (setq package-archives
             '(("original"    . "http://tromey.com/elpa/")
               ("gnu"         . "http://elpa.gnu.org/packages/")
               ("org"         . "http://orgmode.org/elpa/")
               ("marmalade"   . "http://marmalade-repo.org/packages/")))
       (package-initialize)
     #+end_src
     - Packages to be installed by default
     #+begin_src emacs-lisp :tangle no
       ;; Put more packages here if more default should be used.
       ;; This ends up in src/ not el-get/.
       (defvar emacs-init-packages
         (list 'yasnippet-bundle)
         "Libraries that should be installed by default.")

       (unless package-archive-contents
         (package-refresh-contents))
       (dolist (package emacs-init-packages)
         (unless (package-installed-p package)
           (package-install package)))
     #+end_src

   - El-get initialization ::  # <<Lazy Install>>
     - Lazy Install :: To setup el-get the simple way one needs only
       to evaluate the following emacs lisp block
       #+begin_src emacs-lisp :tangle no
         ;; So the idea is that you copy/paste this code into your *scratch* buffer,
         ;; hit C-j, and you have a working el-get.
         (url-retrieve
          "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
          (lambda (s)
            (goto-char (point-max))
            (eval-print-last-sexp)))
       #+end_src
     - Install :: # <<Install>>
       #+begin_src emacs-lisp
         (setq el-get-dir (expand-file-name "el-get" emacs-init-dir))
         (add-to-list 'load-path (concat emacs-init-dir "el-get/el-get"))
         (unless (require 'el-get nil t)
           (url-retrieve
            "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
            (lambda (s)
              (goto-char (point-max))
              (eval-print-last-sexp))))

         (el-get 'sync)
       #+end_src

   - Functions for loading other parts of the emacs init
     #+name: emacs-init-load
     #+begin_src emacs-lisp
       (defun emacs-init-load (file &optional header-or-tag)
         "Load configuration from other emacs-init-*.org files.
       If the optional argument is the id of a subtree then only
       configuration from within that subtree will be loaded.  If it is
       not an id then it will be interpreted as a tag, and only subtrees
       marked with the given tag will be loaded.

       For example, to load all of emacs-init-lisp.org simply
       add (emacs-init-load \"lisp\") to your configuration.
       To load only the 'window-system' config from
       emacs-init-misc-recommended.org add
        (emacs-init-load \"misc-recommended\" \"window-system\")
       to your configuration."
         (let ((file (expand-file-name (if (string-match "emacs-init-.+\.org" file)
                                           file
                                         (format "emacs-init-%s.org" file))
                                       emacs-init-dir)))
           (org-babel-load-file
            (if header-or-tag
                (let* ((base (file-name-nondirectory file))
                       (dir  (file-name-directory file))
                       (partial-file (expand-file-name
                                      (concat "." (file-name-sans-extension base)
                                              ".part." header-or-tag ".org")
                                      dir)))
                  (unless (file-exists-p partial-file)
                    (with-temp-file partial-file
                      (insert
                       (with-temp-buffer
                         (insert-file-contents file)
                         (save-excursion
                           (condition-case nil ;; collect as a header
                               (progn
                                 (org-link-search (concat"#"header-or-tag))
                                 (org-narrow-to-subtree)
                                 (buffer-string))
                             (error ;; collect all entries with as tags
                              (let (body)
                                (org-map-entries
                                 (lambda ()
                                   (save-restriction
                                     (org-narrow-to-subtree)
                                     (setq body (concat body "\n" (buffer-string)))))
                                 header-or-tag)
                                body))))))))
                  partial-file)
              file))))
     #+end_src

* Emacs init core
   :PROPERTIES:
   :CUSTOM_ID: emacs-init-core
   :tangle:   no
   :END:
   The trees contain the remainder of the core of Emacs Init.  All of
   the code in this section should be loaded by emacs used on any
   machine and user.

   - El-get setup and fetch in [[file:emacs-init-el-get.org][emacs-init-el-get]]
     #+begin_src emacs-lisp :tangle no
       (emacs-init-load "emacs-init-el-get.org")
     #+end_src

   - Key Bindings in [[file:emacs-init-bindings.org][emacs-init-bindings]]
     #+begin_src emacs-lisp :tangle no
       (emacs-init-load "emacs-init-bindings.org")
     #+end_src

   - Org Mode settings in [[file:emacs-init-org.org][emacs-init-org]]
     #+begin_src emacs-lisp :tangle no
       (emacs-init-load "emacs-init-org.org")
     #+end_src

   - Miscellaneous settings in [[file:emacs-init-misc.org][emacs-init-misc]]
     #+begin_src emacs-lisp :tangle no
       (emacs-init-load "emacs-init-misc.org")
     #+end_src emacs-lisp

   - Emacs shell settings in [[file:emacs-init-eshell.org][emacs-init-eshell]]
     #+begin_src emacs-lisp :tangle no
       (emacs-init-load "emacs-init-eshell.org")
     #+end_src

   - Publish project on startup, [[file:emacs-init-publish][emacs-init-publish]]
     #+begin_src emacs-lisp :tangle no
       (emacs-init-load "emacs-init-publish.org")
     #+end_src

   - Registers for jumping to commonly used files in [[file:emacs-init-registers.org][emacs-init-registers]]
     #+begin_src emacs-lisp :tangle no
       (emacs-init-load "emacs-init-registers.org")
     #+end_src

   - [[http://code.google.com/p/yasnippet/][yasnippet]] is yet another snippet expansion system for Emacs. It is
     inspired by TextMate's templating syntax.
     - watch the [[http://www.youtube.com/watch?v=vOj7btx3ATg][video on YouTube]]
     - see the [[http://yasnippet.googlecode.com/svn/trunk/doc/index.html][intro and tutorial]]

     load the yasnippet bundle, probably done automatically with el-get
     #+begin_src emacs-lisp :tangle no
       (add-to-list 'load-path
                    (expand-file-name  "yasnippet"
                                       (expand-file-name "el-get"
                                                         emacs-init-dir)))
       (require 'yasnippet)
       (yas/initialize)
     #+end_src

     load the snippets defined in the =./snippets/= directory
     #+begin_src emacs-lisp :tangle no
       (yas/load-directory (expand-file-name "snippets" emacs-init-dir))
     #+end_src

     The latest version of yasnippets doesn't play well with Org-Mode, the
     following function allows these two to play nicely together.
     #+begin_src emacs-lisp
       (defun yas/org-very-safe-expand ()
         (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))

       (defun yas/org-setup ()
         ;; yasnippet (using the new org-cycle hooks)
         (make-variable-buffer-local 'yas/trigger-key)
         (setq yas/trigger-key [tab])
         (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
         (define-key yas/keymap [tab] 'yas/next-field))

       (add-hook 'org-mode-hook #'yas/org-setup)
     #+end_src

* Load User/System Specific Files
  :PROPERTIES:
  :tangle:   no
  :CUSTOM_ID: user-system-configs
  :END:
  You can keep system- or user-specific customizations here in either
  raw emacs-lisp files or as embedded elisp in org-mode files (as done
  in this document).

  You can keep elisp source in the =src= directory. Packages loaded
  from here will override those installed by ELPA. This is useful if
  you want to track the development versions of a project, or if a
  project is not in elpa.

  After we've loaded all the Emacs Init defaults, lets load the User's stuff.
  #+begin_src emacs-lisp
    (flet ((sk-load (base)
  	      (let* ((path          (expand-file-name base emacs-init-dir))
  		     (literate      (concat path ".org"))
  		     (encrypted-org (concat path ".org.gpg"))
  		     (plain         (concat path ".el"))
  		     (encrypted-el  (concat path ".el.gpg")))
  		(cond
  		 ((file-exists-p encrypted-org) (org-babel-load-file encrypted-org))
  		 ((file-exists-p encrypted-el)  (load encrypted-el))
  		 ((file-exists-p literate)      (org-babel-load-file literate))
  		 ((file-exists-p plain)         (load plain)))))
  	    (remove-extension (name)
  	      (string-match "\\(.*?\\)\.\\(org\\(\\.el\\)?\\|el\\)\\(\\.gpg\\)?$" name)
  	      (match-string 1 name)))
      (let ((elisp-dir (expand-file-name "src" emacs-init-dir))
  	     (user-dir (expand-file-name user-login-name emacs-init-dir)))
  	 ;; add the src directory to the load path
  	 (add-to-list 'load-path elisp-dir)
  	 ;; load specific files
  	 (when (file-exists-p elisp-dir)
  	   (let ((default-directory elisp-dir))
  	     (normal-top-level-add-subdirs-to-load-path)))
  	 ;; load system-specific config
  	 (sk-load system-name)
  	 ;; load user-specific config
  	 (sk-load user-login-name)
  	 ;; load any files in the user's directory
  	 (when (file-exists-p user-dir)
  	   (add-to-list 'load-path user-dir)
  	   (mapc #'sk-load
  		 (remove-duplicates
  		  (mapcar #'remove-extension
  			  (directory-files user-dir t ".*\.\\(org\\|el\\)\\(\\.gpg\\)?$"))
  		  :test #'string=)))))
  #+end_src

** Settings from M-x customize
   #+begin_src emacs-lisp
     (load custom-file 'noerror)
   #+end_src


* Footnotes

[1] If you already have a directory at =~/.emacs.d= move it out of the
    way and put this there instead.

[2] The emacs init uses [[http://orgmode.org/][Org Mode]] to load embedded elisp code
    directly from literate Org-mode documents.
